language: python
python:
  - 2.6
  - 2.7
env:
  - DJANGO=django==1.6.11
  - DJANGO=django==1.7.7
  - DJANGO=django==1.8.2
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=django==1.7.7
    - python: 2.6
      env: DJANGO=django==1.8.2
  fast_finish: true
install:
  - travis_retry pip install $DJANGO
  - pip install -e .
script: python runtests.py
notifications:
  email: false
